### ISSUE TITLE
Wrong URL in README.md under SETUP

### ISSUE THREAD

**Issue by unclej84** [OllisGit/OctoPrint-CostEstimation#1]
Hi,

at the bottom of the README.md there is a wrong URL for manual installation:

`https://github.com/OllisGit/OctoPrint-FilamentManager/releases/latest/download/master.zip`

This is a link pointing to FilamentManager.

Regards Jörg

**Comment by ErazerX1** [comment]
Here is the correct one.

https://github.com/OllisGit/OctoPrint-CostEstimation/releases/download/3.0.0/master.zip

**Comment by OllisGit** [comment]
Hi,
thanks a lot!!! The copy and paste error is now fixed.

The URL for the latest release is this: 
```
https://github.com/OllisGit/OctoPrint-CostEstimation/releases/latest/download/master.zip
