### ISSUE TITLE
Cannot set Default Filament Cost (without Filament or Spool Manager Plugin)

### ISSUE THREAD

**Issue by hweigel** [OllisGit/OctoPrint-CostEstimation#10]
Hi Guys,

yeah, pretty much what the title says. I can't set the "default" Filament cost per gram/meter.

Octoprint 1.5.3 running on a Raspberry Pi 3b, CostEstimation version 3.2.

Tried cleanup, tried re-install, all to no avail. See screenshot for further details.

Thanks, cheers, stay safe, hope you can help a noob like me :-)

![CostEstimation3 2 0](https://user-images.githubusercontent.com/60696861/107129881-f0f0e880-68c8-11eb-8d4c-8bc8bb771d0a.png)

**Comment by brandorf** [comment]
Also affected by this, I'm setting up a new printer.  It's estimating the cost using material cost from somewhere, but I can't see it in the UI to change it.

**Comment by MrBill1234** [comment]
Me too.

**Comment by OllisGit** [comment]
Hi,

latest version 3.3.0 fixed this issue. Default values could be set anytime.

Please test and give feedback.

Thx, in advance
Olli

**Comment by hweigel** [comment]
Hi @OllisGit, 

3.3.0 did it, thx for the fix, 's all good man!

Cheers
Helmut

![Clipboard-1](https://user-images.githubusercontent.com/60696861/119309476-a6745b80-bc6e-11eb-8560-93c1e3260b8d.png)
