### ISSUE TITLE
SpoolManager-Plugin implementation

### ISSUE THREAD

**Issue by axelschmidt91** [OllisGit/OctoPrint-CostEstimation#14]
It is cool, that the FilamentManager can be used to estimate the costes of the used filament. As there is another good Plugin that can be used to manage ones filament spools (https://plugins.octoprint.org/plugins/SpoolManager/) I would like to ask if it is possible to implement the use of this plugin as well.

**Comment by Samuel-Martineau** [comment]
It seems to already be supported… 
<img width="593" alt="Screen Shot 2021-08-03 at 10 06 09" src="https://user-images.githubusercontent.com/44237969/128029525-95bb04fa-d383-4a5c-9612-82fa826dd262.png">
