### ISSUE TITLE
Support the Spool Manager Plugin

### ISSUE THREAD

**Issue by WyattNielsen** [OllisGit/OctoPrint-CostEstimation#2]
I would like to use your newer Spool Manager plugin with this. @abrenoch created a pull request in the old location that adds the functionality. Can you pull his work into here?

https://github.com/abrenoch/OctoPrint-CostEstimation/tree/spool-manager

**Comment by WyattNielsen** [comment]
Created a PR from @abrenoch's branch.

**Comment by OllisGit** [comment]
It is now in Version 3.2.0 available.

Please test and give feedback!

**Comment by abrenoch** [comment]
> It is now in Version 3.2.0 available.
> 
> Please test and give feedback!

seems to be working alright for me!
