### ISSUE TITLE
Cost not Displaying 

### ISSUE THREAD

**Issue by jason-a-alexander** [OllisGit/OctoPrint-CostEstimation#4]
For some reason I can not get cost to display.  I have version 3.0 installed.   I have done a removal and reinstall, I have turned off the connection to filament manager and still I don't get a cost.   It looks like the plugin is just not displaying.  I have also removed any plugins that modify the CSS like themify, octoprint-wide, and dashboard.  

![image](https://user-images.githubusercontent.com/52764251/95023144-55fdae80-0649-11eb-958a-58de7efbb545.png)

![image](https://user-images.githubusercontent.com/52764251/95023219-ca385200-0649-11eb-8c91-7a5f6cc83999.png)

Any thoughts?

**Comment by OllisGit** [comment]
Hi @jason-a-alexander,

I released a new version 3.1.0 which output more information about the cost calculation.

This could be for e.g. the following cases:
- user not logged in
- no filament values in meta file 
- ...

Please test the new version, maybe we get a clear view why the costs not shown.

**Comment by jason-a-alexander** [comment]
I installed the new version, and it's now working as expected.
