### ISSUE TITLE
Feature request: Support time estimates in gcode, such as generated by PrusaSlicer M73

### ISSUE THREAD

**Issue by WarrenSchultz** [OllisGit/OctoPrint-CostEstimation#7]
The PrusaSlicer time estimator is much better than the built-in OctoPrint estimator. 

Can you please add a toggle to enable reading the M73 values directly (or interface with the M73 plugin)?
https://github.com/gdombiak/OctoPrint-M73ETAOverride

Thanks!

**Comment by OllisGit** [comment]
Hi @WarrenSchultz,

I think this feature is more related to the Plugin [DisplayLayerProgress](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/).

I raised an issue in that repository: https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/193
